/**
 * registry-meta.mjs
 * Metadata for all Kikito CN components.
 * Used by build-registry.mjs to generate registry JSONs.
 */

/** @type {Record<string, { title: string; description: string; group: string; status: string; }>} */
export const COMPONENT_META = {
  // ── Inputs ──────────────────────────────────────────────────────────
  "accordion":           { title: "Accordion",          group: "display",     description: "Collapsible content sections with animated transitions.",    status: "live" },
  "accordion-group":     { title: "Accordion Group",    group: "display",     description: "Multiple accordions sharing state management.",              status: "live" },
  "autocomplete":        { title: "Autocomplete",       group: "inputs",     description: "Input with real-time filtered suggestions dropdown.",        status: "live" },
  "checkbox":            { title: "Checkbox",           group: "inputs",     description: "Accessible checkbox with indeterminate state support.",       status: "live" },
  "checklist":           { title: "Checklist",          group: "display",     description: "Interactive task list with checkbox items.",                 status: "live" },
  "chip-group":          { title: "Chip Group",         group: "inputs",     description: "Multi-select tag-style chip group.",                         status: "live" },
  "color-picker":        { title: "Color Picker",       group: "inputs",     description: "Visual color selection with hex/rgb/hsl support.",           status: "live" },
  "combobox":            { title: "Combobox",           group: "inputs",     description: "Multi-select combobox with tag chips and keyboard nav.",      status: "live" },
  "currency-input":      { title: "Currency Input",     group: "inputs",     description: "Formatted currency input with locale support.",              status: "live" },
  "date-picker":         { title: "Date Picker",        group: "inputs",     description: "Calendar-based single date selection.",                      status: "live" },
  "date-range-picker":   { title: "Date Range Picker",  group: "inputs",     description: "Calendar-based date range selection.",                       status: "live" },
  "file-upload":         { title: "File Upload",        group: "inputs",     description: "Drag-and-drop file upload with preview and validation.",      status: "live" },
  "floating-label-input":{ title: "Floating Label Input",group:"inputs",     description: "Input with animated floating label on focus.",               status: "live" },
  "input":               { title: "Input",              group: "inputs",     description: "Base text input with variants, states and icons.",           status: "live" },
  "input-group":         { title: "Input Group",        group: "inputs",     description: "Input with prepend/append addons.",                          status: "live" },
  "inline-edit":         { title: "Inline Edit",        group: "inputs",     description: "Click-to-edit inline text field.",                           status: "live" },
  "multi-select":        { title: "Multi Select",       group: "inputs",     description: "Popover-based multi-select with badges.",                    status: "live" },
  "number-input":        { title: "Number Input",       group: "inputs",     description: "Numeric input with increment/decrement controls.",           status: "live" },
  "number-pad":          { title: "Number Pad",         group: "inputs",     description: "PIN-style numeric keypad.",                                  status: "live" },
  "otp-input":           { title: "OTP Input",          group: "inputs",     description: "One-time password input with auto-advance.",                 status: "live" },
  "password-input":      { title: "Password Input",     group: "inputs",     description: "Password input with show/hide toggle.",                     status: "live" },
  "password-strength":   { title: "Password Strength",  group: "display",     description: "Real-time password strength indicator.",                    status: "live" },
  "phone-input":         { title: "Phone Input",        group: "inputs",     description: "International phone number input with country selector.",    status: "live" },
  "radio":               { title: "Radio",              group: "inputs",     description: "Radio button group with label and description.",             status: "live" },
  "range-slider":        { title: "Range Slider",       group: "inputs",     description: "Dual-thumb range slider.",                                  status: "live" },
  "rating":              { title: "Rating",             group: "inputs",     description: "Star rating display component.",                            status: "live" },
  "rating-input":        { title: "Rating Input",       group: "inputs",     description: "Interactive star rating with keyboard support.",             status: "live" },
  "rich-select":         { title: "Rich Select",        group: "inputs",     description: "Select with icons, descriptions and groups.",               status: "live" },
  "search-input":        { title: "Search Input",       group: "inputs",     description: "Search field with icon and clear button.",                  status: "live" },
  "segmented-control":   { title: "Segmented Control",  group: "inputs",     description: "Pill-style option picker.",                                 status: "live" },
  "select":              { title: "Select",             group: "inputs",     description: "Custom select with spring animation, search and groups.",    status: "live" },
  "signature-pad":       { title: "Signature Pad",      group: "inputs",     description: "Canvas-based signature drawing pad.",                       status: "live" },
  "slider":              { title: "Slider",             group: "inputs",     description: "Single-thumb slider with tooltip.",                         status: "live" },
  "survey-form":         { title: "Survey Form",        group: "inputs",     description: "Multi-step form for surveys and feedback.",                 status: "live" },
  "switch":              { title: "Switch",             group: "inputs",     description: "Accessible toggle switch.",                                 status: "live" },
  "tag-input":           { title: "Tag Input",          group: "inputs",     description: "Input that converts text into removable tags.",             status: "live" },
  "textarea":            { title: "Textarea",           group: "inputs",     description: "Auto-resize textarea with character count.",                status: "live" },
  "time-picker":         { title: "Time Picker",        group: "inputs",     description: "Hour/minute/second time selection.",                        status: "live" },
  "toggle-group":        { title: "Toggle Group",       group: "inputs",     description: "Toolbar-style group of toggle buttons.",                    status: "live" },
  "word-counter":        { title: "Word Counter",       group: "display",     description: "Textarea with real-time word and character count.",         status: "live" },

  // ── Display ─────────────────────────────────────────────────────────
  "animated-list":       { title: "Animated List",      group: "display",    description: "List with staggered entrance animations.",                  status: "live" },
  "animated-number":     { title: "Animated Number",    group: "display",    description: "Counter that animates to a target number.",                 status: "live" },
  "avatar":              { title: "Avatar",             group: "display",    description: "User avatar with image, initials and status.",              status: "live" },
  "avatar-group":        { title: "Avatar Group",       group: "display",    description: "Stacked group of avatars with overflow count.",             status: "live" },
  "badge":               { title: "Badge",              group: "inputs",    description: "Status and label badges with variants and intents.",        status: "live" },
  "bento-grid":          { title: "Bento Grid",         group: "layout",    description: "Responsive CSS grid for feature showcases.",               status: "live" },
  "callout":             { title: "Callout",            group: "display",    description: "Highlighted informational block with icon.",                status: "live" },
  "card":                { title: "Card",               group: "display",    description: "Surface card with header, body and footer.",               status: "live" },
  "card-stack":          { title: "Card Stack",         group: "display",    description: "Layered stack of cards with hover interaction.",            status: "live" },
  "carousel":            { title: "Carousel",           group: "display",    description: "Touch-friendly image and content carousel.",               status: "live" },
  "chat-bubble":         { title: "Chat Bubble",        group: "display",    description: "Message bubble for chat interfaces.",                      status: "live" },
  "comparison-table":    { title: "Comparison Table",   group: "data",    description: "Feature comparison matrix.",                               status: "live" },
  "context-card":        { title: "Context Card",       group: "overlays",    description: "Rich hover card with user context.",                       status: "live" },
  "credit-card":         { title: "Credit Card",        group: "display",    description: "3D flip credit card visual.",                              status: "live" },
  "data-list":           { title: "Data List",          group: "data",    description: "Key-value pair list.",                                     status: "live" },
  "event-calendar":      { title: "Event Calendar",     group: "display",    description: "Monthly calendar grid with color-coded event chips and day click handler.", status: "live" },
  "feature-list":        { title: "Feature List",       group: "display",    description: "Icon + text feature/benefit list.",                        status: "live" },
  "flip-card":           { title: "Flip Card",          group: "display",    description: "3D flip card with front and back faces.",                  status: "live" },
  "glass-card":          { title: "Glass Card",         group: "display",    description: "Frosted-glass card effect.",                               status: "live" },
  "glow-card":           { title: "Glow Card",          group: "display",    description: "Card with animated glow/spotlight effect.",                status: "live" },
  "gradient-border":     { title: "Gradient Border",    group: "display",    description: "Animated gradient border wrapper.",                        status: "live" },
  "grid-pattern":        { title: "Grid Pattern",       group: "display",    description: "SVG dot or line grid background pattern.",                 status: "live" },
  "hover-card":          { title: "Hover Card",         group: "display",    description: "Rich preview card shown on hover.",                        status: "live" },
  "icon-box":            { title: "Icon Box",           group: "display",    description: "Styled icon container with background variants.",          status: "live" },
  "image-compare":       { title: "Image Compare",      group: "display",    description: "Before/after image slider.",                               status: "live" },
  "image-cropper":       { title: "Image Cropper",      group: "layout",    description: "Interactive image cropping tool.",                         status: "live" },
  "image-viewer":        { title: "Image Viewer",       group: "display",    description: "Zoomable image viewer with pan support.",                  status: "live" },
  "item":                { title: "Item",               group: "display",    description: "Generic list-row primitive (Item/ItemGroup/ItemMedia/ItemContent/...) for notification, settings and search-result rows.", status: "live" },
  "kanban":              { title: "Kanban",             group: "data",    description: "Drag-and-drop kanban board.",                              status: "live" },
  "masonry":             { title: "Masonry",            group: "layout",    description: "Pinterest-style masonry grid.",                            status: "live" },
  "media-player":        { title: "Media Player",       group: "display",    description: "Custom HTML5 video/audio player.",                         status: "live" },
  "metric-card":         { title: "Metric Card",        group: "display",    description: "Stat card with trend indicator.",                          status: "live" },
  "morphing-text":       { title: "Morphing Text",      group: "display",    description: "Text that morphs between phrases.",                        status: "live" },
  "note-card":           { title: "Note Card",          group: "display",    description: "Sticky-note style card.",                                  status: "live" },
  "particle-field":      { title: "Particle Field",     group: "display",    description: "Canvas-based interactive particle animation.",             status: "live" },
  "pin-board":           { title: "Pin Board",          group: "display",    description: "Draggable pin board with notes.",                          status: "live" },
  "pricing-card":        { title: "Pricing Card",       group: "display",    description: "Subscription plan card with features.",                   status: "live" },
  "pricing-toggle":      { title: "Pricing Toggle",     group: "inputs",    description: "Monthly/annual pricing toggle.",                          status: "live" },
  "price-table":         { title: "Price Table",        group: "display",    description: "Full pricing comparison table.",                          status: "live" },
  "quote-block":         { title: "Quote Block",        group: "display",    description: "Styled blockquote with attribution.",                     status: "live" },
  "receipt-card":        { title: "Receipt Card",       group: "display",    description: "Receipt-style summary card.",                             status: "live" },
  "ribbon":              { title: "Ribbon",             group: "display",    description: "Corner ribbon badge for cards.",                          status: "live" },
  "skill-bar":           { title: "Skill Bar",          group: "charts",    description: "Animated progress bar for skill levels.",                 status: "live" },
  "squish-pricing-card": { title: "Squish Pricing Card", group: "display",   description: "Marketing pricing spotlight card with elastic hover shape.", status: "live" },
  "sparkline":           { title: "Sparkline",          group: "charts",     description: "Inline mini chart.",                                      status: "live" },
  "stat":                { title: "Stat",               group: "display",    description: "Single stat with label and value.",                       status: "live" },
  "stats-card":          { title: "Stats Card",         group: "display",    description: "Card with multiple stats.",                               status: "live" },
  "status-badge":        { title: "Status Badge",       group: "display",    description: "Animated status indicator dot.",                          status: "live" },
  "status-page":         { title: "Status Page",        group: "feedback",    description: "Service status dashboard.",                               status: "live" },
  "swipe-card":          { title: "Swipe Card",         group: "display",    description: "Tinder-style swipeable card.",                            status: "live" },
  "tabs":                { title: "Tabs",               group: "display",    description: "Tab navigation with 4 variants (line/pill/card/enclosed), animated sliding indicator, icons, badges and TabPanel.", status: "live" },
  "tag":                 { title: "Tag",                group: "display",    description: "Removable tag with color variants.",                      status: "live" },
  "tag-cloud":           { title: "Tag Cloud",          group: "display",    description: "Weighted tag cloud visualization.",                       status: "live" },
  "text-effect":         { title: "Text Effect",        group: "display",    description: "Super texto animado: uma entrada que despacha por `effect` para typewriter/morph/gradient/number/shine/wave.", status: "live" },
  "text-shine":          { title: "Text Shine",         group: "display",    description: "Inline text with a static brightness sweep looping across it.", status: "live" },
  "text-wave":           { title: "Text Wave",          group: "display",    description: "Per-character opacity wave shimmer, staggered via motion.", status: "live" },
  "tilt-card":           { title: "Tilt Card",          group: "display",    description: "Card with 3D perspective tilt on hover.",                 status: "live" },
  "timeline":            { title: "Timeline",           group: "display",    description: "Vertical timeline of events.",                            status: "live" },
  "timeline-progress":   { title: "Timeline Progress",  group: "display",    description: "Step-based progress timeline.",                           status: "live" },
  "user-card":           { title: "User Card",          group: "display",    description: "User profile card with avatar and info.",                 status: "live" },
  "video-card":          { title: "Video Card",         group: "display",    description: "Card with video thumbnail and metadata.",                 status: "live" },
  "window-frame":        { title: "Window Frame",       group: "display",    description: "Browser/OS window chrome wrapper.",                       status: "live" },

  // ── Overlay ─────────────────────────────────────────────────────────
  "alert-dialog":        { title: "Alert Dialog",       group: "overlays",    description: "Confirmation dialog requiring user action.",               status: "live" },
  "banner":              { title: "Banner",             group: "feedback",    description: "Full-width site announcement banner.",                    status: "live" },
  "command":             { title: "Command",            group: "overlays",    description: "Command palette with fuzzy search.",                      status: "live" },
  "command-bar":         { title: "Command Bar",        group: "overlays",    description: "Keyboard-shortcut command bar.",                          status: "live" },
  "confirm-button":      { title: "Confirm Button",     group: "feedback",    description: "Button with inline confirmation step.",                   status: "live" },
  "context-menu":        { title: "Context Menu",       group: "overlays",    description: "Right-click context menu.",                               status: "live" },
  "drawer":              { title: "Drawer",             group: "overlays",    description: "Slide-in side panel drawer.",                             status: "live" },
  "dropdown-menu":       { title: "Dropdown Menu",      group: "overlays",    description: "Trigger-based dropdown with sections and icons.",         status: "live" },
  "modal":               { title: "Modal",              group: "overlays",    description: "Accessible modal dialog with portal.",                    status: "live" },
  "notice-bar":          { title: "Notice Bar",         group: "feedback",    description: "Sticky notice bar with dismiss.",                        status: "live" },
  "onboarding-tour":     { title: "Onboarding Tour",    group: "feedback",    description: "Step-by-step product tour overlay.",                     status: "live" },
  "popover":             { title: "Popover",            group: "overlays",    description: "Positioned popover with arrow.",                         status: "live" },
  "rich-tooltip":        { title: "Rich Tooltip",       group: "overlays",    description: "Tooltip with rich content and image.",                   status: "live" },
  "spotlight-search":    { title: "Spotlight Search",   group: "overlays",    description: "Full-screen spotlight-style search palette.",             status: "live" },
  "toast":               { title: "Toast",              group: "feedback",    description: "Toast notification system with context API.",             status: "live" },
  "tooltip":             { title: "Tooltip",            group: "overlays",    description: "Simple hover tooltip.",                                  status: "live" },

  // ── Navigation ──────────────────────────────────────────────────────
  "breadcrumb":          { title: "Breadcrumb",         group: "display", description: "Location breadcrumb with separator.",                    status: "live" },
  "dot-stepper":         { title: "Dot Stepper",        group: "display", description: "Dot-indicator step progress.",                           status: "live" },
  "fab":                 { title: "FAB",                group: "inputs", description: "Floating action button with sub-actions.",               status: "live" },
  "filter-bar":          { title: "Filter Bar",         group: "inputs", description: "Horizontal filter pill bar.",                            status: "live" },
  "floating-bar":        { title: "Floating Bar",       group: "layout", description: "Floating toolbar that appears on selection.",            status: "live" },
  "floating-menu":       { title: "Floating Menu",      group: "overlays", description: "Animated floating radial menu.",                         status: "live" },
  "keyboard-shortcuts":  { title: "Keyboard Shortcuts", group: "display", description: "Keyboard shortcut legend dialog.",                       status: "live" },
  "navigation-menu":     { title: "Navigation Menu",    group: "layout", description: "Horizontal nav with dropdowns.",                         status: "live" },
  "pagination":          { title: "Pagination",         group: "data", description: "Page navigation with page size control.",                status: "live" },
  "quick-actions":       { title: "Quick Actions",      group: "overlays", description: "Speed-dial style quick action buttons.",                 status: "live" },
  "scroll-progress":     { title: "Scroll Progress",    group: "layout", description: "Reading progress bar tied to scroll.",                   status: "live" },
  "scroll-spy":          { title: "Scroll Spy",         group: "layout", description: "Highlights nav items based on scroll position.",         status: "live" },
  "scroll-timeline":     { title: "Scroll Timeline",    group: "display", description: "CSS scroll-timeline animations.",                        status: "live" },
  "shortcut-key":        { title: "Shortcut Key",       group: "display", description: "Keyboard shortcut display.",                             status: "live" },
  "side-panel":          { title: "Side Panel",         group: "layout", description: "Resizable side panel layout.",                          status: "live" },
  "sortable-list":       { title: "Sortable List",      group: "layout", description: "Drag-to-reorder list.",                                 status: "live" },
  "stepper":             { title: "Stepper",            group: "display", description: "Multi-step wizard navigation.",                         status: "live" },
  "table-of-contents":   { title: "Table of Contents",  group: "layout", description: "Auto-generated TOC from headings.",                     status: "live" },
  "vertical-nav":        { title: "Vertical Nav",       group: "layout", description: "Sidebar vertical navigation.",                          status: "live" },

  // ── Data ────────────────────────────────────────────────────────────
  "data-grid":           { title: "Data Grid",          group: "data",       description: "High-performance editable data grid with virtualization.", status: "live" },
  "infinite-scroll":     { title: "Infinite Scroll",    group: "layout",       description: "Load-on-scroll data fetching.",                          status: "live" },
  "json-viewer":         { title: "JSON Viewer",        group: "data",       description: "Collapsible JSON tree viewer.",                          status: "live" },
  "log-viewer":          { title: "Log Viewer",         group: "feedback",       description: "Real-time log stream viewer.",                           status: "live" },
  "table":               { title: "Table",              group: "data",       description: "Sortable data table.",                                   status: "live" },
  "tree-table":          { title: "Tree Table",         group: "data",       description: "Expandable hierarchical table.",                         status: "live" },
  "tree-view":           { title: "Tree View",          group: "data",       description: "File-explorer-style tree.",                              status: "live" },
  "virtual-list":        { title: "Virtual List",       group: "data",       description: "Virtualized list for large datasets.",                   status: "live" },

  // ── Charts ──────────────────────────────────────────────────────────
  "area-chart":          { title: "Area Chart",         group: "charts",     description: "Filled area chart.",                                     status: "live" },
  "bar-chart":           { title: "Bar Chart",          group: "charts",     description: "Vertical and horizontal bar chart.",                     status: "live" },
  "chart":               { title: "Chart",              group: "charts",     description: "Super grafico: uma entrada que despacha por `type` para line/area/bar/donut/pie/radar/radial-bar/funnel/sparkline.", status: "live" },
  "donut-chart":         { title: "Donut Chart",        group: "charts",     description: "Donut/pie chart.",                                       status: "live" },
  "funnel-chart":        { title: "Funnel Chart",       group: "charts",     description: "Funnel/conversion chart.",                              status: "live" },
  "gauge":               { title: "Gauge",              group: "charts",     description: "Arc gauge meter.",                                       status: "live" },
  "line-chart":          { title: "Line Chart",         group: "charts",     description: "Line and curve chart.",                                  status: "live" },
  "pie-chart":           { title: "Pie Chart",          group: "charts",     description: "ECharts pie chart (filled slices, no hole) with segments and legend.", status: "live" },
  "radar-chart":         { title: "Radar Chart",        group: "charts",     description: "Multi-axis radar/spider chart.",                         status: "live" },
  "radial-bar-chart":    { title: "Radial Bar Chart",   group: "charts",     description: "Multi-series radial bar chart (concentric arcs) powered by the shared ECharts infrastructure.", status: "live" },

  // ── Feedback ────────────────────────────────────────────────────────
  "alert":               { title: "Alert",              group: "feedback",   description: "Inline alert with variants and dismiss.",                status: "live" },
  "empty-state":         { title: "Empty State",        group: "display",   description: "Empty content placeholder with action.",                 status: "live" },
  "feedback-widget":     { title: "Feedback Widget",    group: "feedback",   description: "Floating user feedback collector.",                      status: "live" },
  "notification-bell":   { title: "Notification Bell",  group: "feedback",   description: "Notification bell with badge count.",                    status: "live" },
  "ping":                { title: "Ping",               group: "display",   description: "Animated ping dot for live indicators.",                 status: "live" },
  "progress":            { title: "Progress",           group: "feedback",   description: "Linear progress bar with variants.",                     status: "live" },
  "progress-ring":       { title: "Progress Ring",      group: "feedback",   description: "Circular SVG progress ring.",                            status: "live" },
  "progress-steps":      { title: "Progress Steps",     group: "display",   description: "Step-based progress indicator.",                         status: "live" },
  "skeleton":            { title: "Skeleton",           group: "feedback",   description: "Content loading placeholder skeleton.",                  status: "live" },
  "spinner":             { title: "Spinner",            group: "feedback",   description: "Loading spinner with sizes.",                            status: "live" },

  // ── Layout ──────────────────────────────────────────────────────────
  "aspect-ratio":        { title: "Aspect Ratio",       group: "layout",     description: "Maintains aspect ratio of child content.",              status: "live" },
  "collapsible":         { title: "Collapsible",        group: "display",     description: "Animated expand/collapse section.",                     status: "live" },
  "draggable":           { title: "Draggable",          group: "layout",     description: "Drag-and-drop wrapper.",                                status: "live" },
  "form-field":          { title: "Form Field",         group: "inputs",     description: "Label + input + helper text wrapper.",                  status: "live" },
  "label":               { title: "Label",              group: "inputs",     description: "Form label with required indicator.",                   status: "live" },
  "menubar":             { title: "Menubar",            group: "layout",     description: "Desktop-style horizontal app menu bar (File/Edit/View) with click-and-hover-to-switch menus.", status: "live" },
  "multi-accordion":     { title: "Multi Accordion",    group: "display",     description: "Multiple independently expandable accordions.",          status: "live" },
  "resizable":           { title: "Resizable",          group: "layout",     description: "Resizable panel layout.",                               status: "live" },
  "scroll-area":         { title: "Scroll Area",        group: "layout",     description: "Overflow container with styled scrollbar.",              status: "live" },
  "scroll-reveal":       { title: "Scroll Reveal",      group: "layout",     description: "Animate children on scroll into view.",                 status: "live" },
  "separator":           { title: "Separator",          group: "layout",     description: "Horizontal or vertical divider.",                       status: "live" },
  "step-form":           { title: "Step Form",          group: "inputs",     description: "Multi-step form with validation per step.",             status: "live" },

  // ── Buttons & Actions ────────────────────────────────────────────────
  "button":              { title: "Button",             group: "inputs",     description: "Button with variants, intents, sizes and loading state.", status: "live" },
  "button-group":        { title: "Button Group",       group: "inputs",     description: "Grouped button set sharing borders.",                   status: "live" },
  "confetti-button":     { title: "Confetti Button",    group: "feedback",     description: "Button that triggers confetti on click.",               status: "live" },
  "copy-button":         { title: "Copy Button",        group: "display",     description: "Copy-to-clipboard button with feedback.",               status: "live" },
  "magnetic-button":     { title: "Magnetic Button",    group: "feedback",     description: "Button with magnetic cursor attraction effect.",        status: "live" },
  "split-button":        { title: "Split Button",       group: "inputs",     description: "Button with dropdown for secondary actions.",           status: "live" },
  "countdown-timer":     { title: "Countdown Timer",    group: "feedback",    description: "Countdown to a target date/time.",                      status: "live" },
  "stopwatch":           { title: "Stopwatch",          group: "feedback",    description: "Start/stop/reset stopwatch.",                           status: "live" },

  // ── Text & Content ───────────────────────────────────────────────────
  "code-block":          { title: "Code Block",         group: "display",    description: "Syntax-highlighted code block with copy.",              status: "live" },
  "code-diff":           { title: "Code Diff",          group: "data",    description: "Side-by-side or inline code diff.",                     status: "live" },
  "kbd":                 { title: "Kbd",                group: "display",    description: "Keyboard key display element.",                         status: "live" },
  "markdown-renderer":   { title: "Markdown Renderer",  group: "display",    description: "Renders markdown to styled HTML.",                      status: "live" },
  "marquee-text":        { title: "Marquee Text",       group: "display",    description: "Infinite scrolling text marquee.",                      status: "live" },
  "morphing-text":       { title: "Morphing Text",      group: "display",    description: "Smoothly morphs between text values.",                  status: "live" },
  "read-more":           { title: "Read More",          group: "display",    description: "Truncated text with expand/collapse.",                  status: "live" },
  "terminal-block":      { title: "Terminal Block",     group: "display",    description: "Terminal emulator display.",                            status: "live" },
  "text-editor":         { title: "Text Editor",        group: "inputs",     description: "Rich text WYSIWYG editor.",                             status: "live" },
  "text-gradient":       { title: "Text Gradient",      group: "display",    description: "CSS gradient text effect.",                             status: "live" },
  "typewriter":          { title: "Typewriter",         group: "display",    description: "Animated typewriter text effect.",                      status: "live" },

  // ── Misc ─────────────────────────────────────────────────────────────
  "activity-feed":       { title: "Activity Feed",      group: "display",    description: "User activity timeline feed.",                          status: "live" },
  "audio-waveform":      { title: "Audio Waveform",     group: "display",    description: "Audio playback with waveform visualization.",           status: "live" },
  "calendar":            { title: "Calendar",           group: "inputs",     description: "Full calendar with event support.",                     status: "live" },
  "mini-map":            { title: "Mini Map",           group: "layout",    description: "Miniature overview map.",                               status: "live" },
  "newsletter-form":     { title: "Newsletter Form",    group: "inputs",     description: "Email subscription form.",                              status: "live" },
  "spotlight":           { title: "Spotlight",          group: "display",    description: "Cursor-tracking spotlight effect.",                     status: "live" },
  "theme-selector":      { title: "Theme Selector",     group: "display",    description: "Light/dark/system theme switcher.",                     status: "live" },
};

/** Components to skip (internal/showcase only) */
export const SKIP_COMPONENTS = new Set([
  "tokens",
  "aceternity-cards-demo-3",
  "aceternity-features-section",
  // Helpers internos do próprio site de docs (/cn) — não fazem parte do
  // registry publicado, não devem cair no fallback group:"display" default.
  "cn-install-block",
  "cn-props-table",
  "cn-source-block",
  "cn-usage-block",
]);

/** Component name → npm package mapping */
export const NPM_DEP_MAP = {
  "motion/react": "motion",
  "framer-motion": "framer-motion",
  "next-themes": "next-themes",
  "lucide-react": "lucide-react",
  "recharts": "recharts",
  "echarts": "echarts",
  "embla-carousel-react": "embla-carousel-react",
  "embla-carousel": "embla-carousel",
  "@dnd-kit/core": "@dnd-kit/core",
  "@dnd-kit/sortable": "@dnd-kit/sortable",
  "@dnd-kit/utilities": "@dnd-kit/utilities",
  "@dnd-kit/modifiers": "@dnd-kit/modifiers",
  "cmdk": "cmdk",
  "vaul": "vaul",
  "input-otp": "input-otp",
  "sonner": "sonner",
  "class-variance-authority": "class-variance-authority",
  "react-resizable-panels": "react-resizable-panels",
  "react-day-picker": "react-day-picker",
  "date-fns": "date-fns",
  "@radix-ui/react-icons": "@radix-ui/react-icons",
  "kbar": "kbar",
  "simplex-noise": "simplex-noise",
  "zod": "zod",
  "@tiptap/react": "@tiptap/react",
  "@tiptap/starter-kit": "@tiptap/starter-kit",
  "@tiptap/core": "@tiptap/core",
};
